version: '3.8'

services:
  # Blog Database service
  blog-db:
    image: "mysql"  # Use the official MySQL image
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  # Use the root password from environment variables
    volumes:
      - blog-db-vol:/var/lib/mysql  # Persist MySQL data in a named volume
    ports:
      - "3306:3306"  # Expose MySQL port 3306
    networks:
      - blog-app-net
  # Blog Server service
  blog-server:
    build:
      dockerfile: Dockerfile  # Use the Dockerfile in the current directory
      context: .  # Build context is the current directory
    container_name: blog-app-container  # Name for the container
    ports:
      - "3001:3002"  # Map host port 3001 to container port 3002, so access app via http://localhost:3001
    env_file:
      - ./.env  # Load environment variables from the .env file
    volumes:
      - ./:/app  # Mount the project directory into the container at /app
      # - ./certs:/certs  # Mount SSL certificate directory into the container
    depends_on:
      - blog-db  # Ensure blog-db service is up before blog-server starts
    networks:
      - blog-app-net

# Named volume for MySQL data persistence
volumes:
  blog-db-vol:
networks:
  blog-app-net: