name: Bloggy CD
on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      IMAGE_NAME: bikramraidocker/blog-app
      IMAGE_TAG: build-${{ github.run_number }} # bikramraidocker/     blog-app:v1, v2, v3
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
        with:
          persist-credentials: true
      - name: Build docker image
        run: docker build -t ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} --platform linux/amd64 .
      - name: Login into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push docker image to Docker Hub
        run: docker push ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@v0.16.1
        with:
          valueFile: compose.yaml
          propertyPath: 'services["blog-server"].image'
          value: ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
          commitChange: false
      - name: Commit the changes
        run: |
          git config user.name github-actions
          git config user.email githubaction@github.com
          git add .
          git commit -m "bump the image version ${{env.IMAGE_TAG}}"
          git push origin main

  deploy:
    name: Deploy the image to Docker Swarm Cluster
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: bikramraidocker/blog-app
      IMAGE_TAG: build-${{github.run_number}}
    needs:
      - build-and-push

    steps:
      - name: SSH into the server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SWARM_MANAGER_HOST }} # host id (public EC2 manager)
          username: ${{secrets.SWARM_HOST_USERNAME}}
          key: ${{secrets.SWARM_HOST_SSH_KEY}}
          port: ${{secrets.SWARM_HOST_SSH_PORT}} #ssh default : 22
          script: |
            # Exit immediately if a command exits with a non-zero status
            set -e
            # Navigate to the project directory on the server (manager root/)
            # cd ~/bloggy
            cd /home/ubuntu/bloggy


            # Update the project files from the latest main branch
            git fetch origin main
            git checkout origin/main

            # Pull the latest Docker image from Docker Hub
            docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

            # Deploy the updated stack using Docker Compose
            docker stack deploy -c compose.yaml bloggy
